---
- name: Get All repositories
  nexus_repository_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'beta'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: GET
#- name: Delete 1 repository
#  nexus_repository_api:
#    url: http://10.10.3.144:8081
#    endpoint_version: 'beta'
#    url_username: 'admin'
#    url_password: 'Potato1234'
#    headers: 
#      accept: "application/json"
#    force_basic_auth: yes
#    validate_certs: false
#    method: DELETE
#    repository_info:
#      name: RHEL8