---
- name: Get All scripts
  nexus_script_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'v1'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: GET
- name: Get create task scripts
  nexus_script_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'v1'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: GET
    script_info:
      name: create_task
- name: Get create task scripts
  nexus_script_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'v1'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: GET
    script_info:
      name: create_blobstores_from_list  
- name: Post a script
  nexus_script_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'v1'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
      Content-Type: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: POST
    script_info:
      name: create_blobstores_from_list
      content: "{{ lookup('file', 'files/groovy/create_blobstores_from_list.groovy') }}"
      content_type: 'groovy'
- name: Put a script without it previously existing
  nexus_script_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'v1'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
      Content-Type: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: POST
    script_info:
      name: a_thing_that_I_do
      content: "{{ lookup('file', 'files/groovy/create_blobstores_from_list.groovy') }}"
      content_type: 'groovy'
- name: Delete a script
  nexus_script_api:
    url: http://10.10.3.144:8081
    endpoint_version: 'v1'
    url_username: 'admin'
    url_password: 'Potato1234'
    headers: 
      accept: "application/json"
      Content-Type: "application/json"
    force_basic_auth: yes
    validate_certs: false
    method: DELETE
    script_info:
      name: a_thing_that_I_do
      content: "{{ lookup('file', 'files/groovy/create_blobstores_from_list.groovy') }}"
      content_type: 'groovy'